In [1]:
import numpy as np

# Define matrices A and B
A = np.array([[2, -1], [0, 3]])
B = np.array([[1, 2], [-3, 4]])

# A + B
result1 = A + B
print("A + B:\n", result1)

#  AB 
result2 = np.dot(A, B)  
print("AB:\n", result2)

# 3A - 2B
result3 = 3 * A - 2 * B
print("3A - 2B:\n", result3)

A + B:
 [[ 3  1]
 [-3  7]]
AB:
 [[ 5  0]
 [-9 12]]
3A - 2B:
 [[ 4 -7]
 [ 6  1]]


In [2]:
# Define matrix A
A = np.array([[2, -1], [0, 3]])

# determinant of A
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# Check if A is invertible 
if det_A != 0:
    # Calculate the inverse of A
    A_inv = np.linalg.inv(A)
    print("Inverse of A:\n", A_inv)
else:
    print("Matrix A is not invertible.")

Determinant of A: 6.0
Inverse of A:
 [[0.5        0.16666667]
 [0.         0.33333333]]


In [3]:
#define the matrix c
C = np.array([[4,1],
              [-2,1]])
#eigen value and eigen vector
eigval,eigvec = np.linalg.eig(A)
print(f"eigen values of matrix A is {eigval}")
print(f"eigen vectors of matrix A is {eigvec}")

eigen values of matrix A is [2. 3.]
eigen vectors of matrix A is [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


In [4]:
S= np.array([[4,1.5,100], #feature for car1
              [6,2.0,150]]) #feature for car2
P = np.array([[20],       #price for car1 and car2
              [30]])
inv = np.linalg.pinv(S.T @ S)
B = inv @ S.T @ P
X = np.array([[8,3.0,200]])
pri= np.linalg.det(X @ B)
print(f" price of the car X3 is {pri}") #price for car3

 price of the car X3 is 40.00000000000069
